# Generated by Django 6.1.1 on 2026-09-19 13:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Oturum Anahtarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Alışveriş Sepeti',
                'verbose_name_plural': 'Alışveriş Sepetleri',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='SEO URL (Slug)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kategori Görseli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_featured_home', models.BooleanField(default=False, verbose_name='Anasayfada Öne Çıkar')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Sipariş No')),
                ('first_name', models.CharField(max_length=60, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=60, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('address_title', models.CharField(default='Ev Adresim', max_length=40, verbose_name='Adres Başlığı')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Açık Adres (Cadde, Sokak, No, Daire)')),
                ('address_line2', models.CharField(blank=True, max_length=100, verbose_name='Bina / Kat / Ek Bilgi')),
                ('district', models.CharField(max_length=60, verbose_name='İlçe')),
                ('city', models.CharField(max_length=60, verbose_name='İl / Şehir')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu')),
                ('order_notes', models.TextField(blank=True, verbose_name='Sipariş / Kurye Notu')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ara Toplam (TL)')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kargo Ücreti (TL)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Genel Toplam (TL)')),
                ('status', models.CharField(choices=[('pending', 'Ödeme Bekleniyor'), ('confirmed', 'Sipariş Onaylandı'), ('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='pending', max_length=20, verbose_name='Sipariş Durumu')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kredi / Banka Kartı (PayTR / İyzico - Max 3 Taksit)'), ('bank_transfer', 'Havale / EFT (Ön Onaylı)'), ('cash_on_delivery', 'Kapıda Nakit / Kart ile Ödeme (+19.90 TL Hizmet Bedeli)')], default='credit_card', max_length=30, verbose_name='Ödeme Yöntemi')),
                ('payment_status', models.CharField(choices=[('pending', 'Ödeme Bekleniyor'), ('paid', 'Ödendi / Başarılı'), ('failed', 'Ödeme Başarısız')], default='pending', max_length=20, verbose_name='Ödeme Durumu')),
                ('installments', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Taksit Sayısı (Maksimum 3)')),
                ('cargo_company', models.CharField(default='Yurtiçi Kargo', max_length=50, verbose_name='Kargo Firması')),
                ('tracking_number', models.CharField(blank=True, max_length=80, verbose_name='Kargo Takip No')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri Hesabı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paytr', 'PayTR Sanal POS'), ('iyzico', 'İyzico Checkout API'), ('bank_transfer', 'Havale / EFT Bildirimi'), ('cash_on_delivery', 'Kapıda Ödeme Tahsilatı')], default='paytr', max_length=30, verbose_name='Ödeme Sağlayıcı')),
                ('transaction_id', models.CharField(blank=True, max_length=120, verbose_name='İşlem / Dekont No')),
                ('status', models.CharField(choices=[('success', 'Başarılı (Tahsil Edildi)'), ('failed', 'Başarısız (Hata Alındı)'), ('pending', 'İşlem Sürüyor'), ('refunded', 'İade Edildi')], default='pending', max_length=20, verbose_name='İşlem Durumu')),
                ('installment_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3, message='Tekstil ve giyim mevzuatı gereği taksit sayısı en fazla 3 olabilir.')], verbose_name='Taksit Sayısı (Maks. 3 Taksit Kuralı)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Tutar (TL)')),
                ('card_family', models.CharField(blank=True, max_length=50, verbose_name='Kart Programı (Bonus, World, Axess, vb.)')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='Kart Son 4 Hane')),
                ('raw_response', models.TextField(blank=True, verbose_name='API Ham Yanıt (JSON/XML)')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Detayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='store.order', verbose_name='İlişkili Sipariş')),
            ],
            options={
                'verbose_name': 'Ödeme Kaydı (Payment Log)',
                'verbose_name_plural': 'Ödeme Kayıtları (Payment Logs)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='SEO URL (Slug)')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='Ürün Kodu (SKU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Satış Fiyatı (TL)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='İndirimli Fiyat (TL)')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kısa Özet')),
                ('description', models.TextField(verbose_name='Detaylı Ürün Açıklaması')),
                ('fabric_info', models.TextField(blank=True, help_text='Örn: %95 Viskon, %5 Elastan. Likralı, dökümlü ve terletmeyen kumaş.', verbose_name='Kumaş ve Materyal Bilgisi')),
                ('washing_instructions', models.TextField(blank=True, default='30 derecede hassas yıkama yapınız. Ağartıcı kullanmayınız. Düşük ısıda tersten ütüleyiniz.', verbose_name='Yıkama ve Bakım Talimatı')),
                ('model_measurements', models.TextField(blank=True, help_text='Örn: Manken Ölçüleri: Boy: 1.74m, Göğüs: 104cm, Bel: 86cm, Basen: 112cm. Giydiği Beden: 44/XL. Kalıp: Rahat / Tam Kalıp.', verbose_name='Manken & Kalıp Bilgileri')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Çok Satan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_new', models.BooleanField(default=True, verbose_name='Yeni Sezon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta / Aktif')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Ürün Adı')),
                ('size_title', models.CharField(max_length=80, verbose_name='Beden Seçimi')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (TL)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat (TL)')),
                ('product_image_url', models.CharField(blank=True, max_length=500, verbose_name='Ürün Görsel URL')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Görsel')),
                ('image_url_fallback', models.URLField(blank=True, max_length=500, verbose_name='Harici Görsel Linki (Opsiyonel)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Görsel Açıklaması (Alt Tag)')),
                ('is_feature', models.BooleanField(default=False, verbose_name='Kapak Görseli mi?')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['-is_feature', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Standart', 'Standart Beden (38-44 Uyumlu)'), ('M (38-40)', 'M (38-40)'), ('L (40-42)', 'L (40-42)'), ('XL (42-44)', 'XL (42-44) - Büyük Beden'), ('2XL (46-48)', '2XL (46-48) - Büyük Beden'), ('3XL (50-52)', '3XL (50-52) - Büyük Beden'), ('4XL (54-56)', '4XL (54-56) - Büyük Beden'), ('5XL (58-60)', '5XL (58-60) - Büyük Beden'), ('42', '42 Beden'), ('44', '44 Beden'), ('46', '46 Beden'), ('48', '48 Beden'), ('50', '50 Beden'), ('52', '52 Beden'), ('54', '54 Beden'), ('56', '56 Beden')], max_length=30, verbose_name='Beden / Boyut')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Stok Miktarı')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='Beden Barkodu / Özel SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışa Açık')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='store.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Beden Varyantı',
                'verbose_name_plural': 'Beden Varyantları',
                'ordering': ['size'],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='Sepet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Ürün')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sizevariant', verbose_name='Seçilen Beden')),
            ],
            options={
                'verbose_name': 'Sepet Öğesi',
                'verbose_name_plural': 'Sepet Öğeleri',
            },
        ),
    ]
